### ISSUE TITLE
Release build does not work.

### ISSUE THREAD

**Issue by p0int3r** [Archie3d/qpdf#22]
When i compile the project via the qt creator using debug mode everything works fine.
But when i change to release i get the following error:

js: Uncaught ReferenceError: qpdf_Initialize is not defined

Any idea why that might happen. Thanks in advance.

**Comment by Schwarzbierbaron** [comment]
Same here (Qt 5.13.1, Creator 4.10.2, Windows). Additionally it does not find pdf.js and viewer.js in the viewer.html in release build.
It seems to be a problem with the resource management. If I switch from qrc to a local file (change cPdfViewerUrl to a local path) everything works fine.

**Comment by Archie3d** [comment]
@Schwarzbierbaron Can you run a simple application that shows a web page loaded from resources?
As you may see there is no difference between debug and release in the code, and I cannot reproduce the problem unfortunately.

**Comment by obiwankennedy** [comment]
I have the same issue on windows 10. Linux works fine!

I can see the web page, with all buttons, the dark background, but the pdf content stays empty.

I can reproduce the issue with pdfviewer from this git repo, in release. 
It is compiled with vs15 (2017) in 64bits with Qt5.14 (or Qt5.12).

I will try to load stuff from disk, I let you know.

**Comment by Archie3d** [comment]
Ok, I think I know where the problem is.
It is actually QtCreator messing up with JavaScript files and treats them as QML resources when compiled in Release (for some reason). You need to go to the project build settings and disable Qt Quick compiler:
<img width="518" alt="disable_qml" src="https://user-images.githubusercontent.com/5774953/74587365-6ba26300-4fe9-11ea-9414-ff661ee149ac.png">

By default it is disabled for Windows Debug builds, but gets enabled automatically on Release switch. I guess Qt Creator discovers `*.js` files in the project and thinks it's QML.

**Comment by obiwankennedy** [comment]
That right, this fix my issues.
